/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (string | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (string | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (string | null) | User;
  customerEmail?: string | null;
  transactions?: (string | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'USD' | null;
  accessToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: string | Media;
        variantOption?: (string | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (string | VariantType)[] | null;
  variants?: {
    docs?: (string | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  relatedProducts?: (string | Product)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  categories?: (string | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: string;
  _variantOptions_options_order?: string | null;
  variantType: string | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: string;
  label: string;
  name: string;
  options?: {
    docs?: (string | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  refCategory?: (string | null) | Category;
  icon?:
    | (
        | 'a-arrow-down'
        | 'a-arrow-up'
        | 'a-large-small'
        | 'accessibility'
        | 'activity'
        | 'air-vent'
        | 'airplay'
        | 'alarm-clock-check'
        | 'alarm-check'
        | 'alarm-clock-minus'
        | 'alarm-minus'
        | 'alarm-clock-off'
        | 'alarm-clock-plus'
        | 'alarm-plus'
        | 'alarm-clock'
        | 'alarm-smoke'
        | 'album'
        | 'align-center-horizontal'
        | 'align-center-vertical'
        | 'align-center'
        | 'align-end-horizontal'
        | 'align-end-vertical'
        | 'align-horizontal-distribute-center'
        | 'align-horizontal-distribute-end'
        | 'align-horizontal-distribute-start'
        | 'align-horizontal-justify-center'
        | 'align-horizontal-justify-end'
        | 'align-horizontal-justify-start'
        | 'align-horizontal-space-around'
        | 'align-horizontal-space-between'
        | 'align-justify'
        | 'align-left'
        | 'align-right'
        | 'align-start-horizontal'
        | 'align-start-vertical'
        | 'align-vertical-distribute-center'
        | 'align-vertical-distribute-end'
        | 'align-vertical-distribute-start'
        | 'align-vertical-justify-center'
        | 'align-vertical-justify-end'
        | 'align-vertical-justify-start'
        | 'align-vertical-space-around'
        | 'align-vertical-space-between'
        | 'ambulance'
        | 'ampersand'
        | 'ampersands'
        | 'amphora'
        | 'anchor'
        | 'angry'
        | 'annoyed'
        | 'antenna'
        | 'anvil'
        | 'aperture'
        | 'app-window-mac'
        | 'app-window'
        | 'apple'
        | 'archive-restore'
        | 'archive-x'
        | 'archive'
        | 'armchair'
        | 'arrow-big-down-dash'
        | 'arrow-big-down'
        | 'arrow-big-left-dash'
        | 'arrow-big-left'
        | 'arrow-big-right-dash'
        | 'arrow-big-right'
        | 'arrow-big-up-dash'
        | 'arrow-big-up'
        | 'arrow-down-0-1'
        | 'arrow-down-01'
        | 'arrow-down-1-0'
        | 'arrow-down-10'
        | 'arrow-down-a-z'
        | 'arrow-down-az'
        | 'arrow-down-from-line'
        | 'arrow-down-left'
        | 'arrow-down-narrow-wide'
        | 'arrow-down-right'
        | 'arrow-down-to-dot'
        | 'arrow-down-to-line'
        | 'arrow-down-up'
        | 'arrow-down-wide-narrow'
        | 'sort-desc'
        | 'arrow-down-z-a'
        | 'arrow-down-za'
        | 'arrow-down'
        | 'arrow-left-from-line'
        | 'arrow-left-right'
        | 'arrow-left-to-line'
        | 'arrow-left'
        | 'arrow-right-from-line'
        | 'arrow-right-left'
        | 'arrow-right-to-line'
        | 'arrow-right'
        | 'arrow-up-0-1'
        | 'arrow-up-01'
        | 'arrow-up-1-0'
        | 'arrow-up-10'
        | 'arrow-up-a-z'
        | 'arrow-up-az'
        | 'arrow-up-down'
        | 'arrow-up-from-dot'
        | 'arrow-up-from-line'
        | 'arrow-up-left'
        | 'arrow-up-narrow-wide'
        | 'sort-asc'
        | 'arrow-up-right'
        | 'arrow-up-to-line'
        | 'arrow-up-wide-narrow'
        | 'arrow-up-z-a'
        | 'arrow-up-za'
        | 'arrow-up'
        | 'arrows-up-from-line'
        | 'asterisk'
        | 'at-sign'
        | 'atom'
        | 'audio-lines'
        | 'audio-waveform'
        | 'award'
        | 'axe'
        | 'axis-3d'
        | 'axis-3-d'
        | 'baby'
        | 'backpack'
        | 'badge-alert'
        | 'badge-cent'
        | 'badge-check'
        | 'verified'
        | 'badge-dollar-sign'
        | 'badge-euro'
        | 'badge-indian-rupee'
        | 'badge-info'
        | 'badge-japanese-yen'
        | 'badge-minus'
        | 'badge-percent'
        | 'badge-plus'
        | 'badge-pound-sterling'
        | 'badge-question-mark'
        | 'badge-help'
        | 'badge-russian-ruble'
        | 'badge-swiss-franc'
        | 'badge-turkish-lira'
        | 'badge-x'
        | 'badge'
        | 'baggage-claim'
        | 'ban'
        | 'banana'
        | 'bandage'
        | 'banknote-arrow-down'
        | 'banknote-arrow-up'
        | 'banknote-x'
        | 'banknote'
        | 'barcode'
        | 'barrel'
        | 'baseline'
        | 'bath'
        | 'battery-charging'
        | 'battery-full'
        | 'battery-low'
        | 'battery-medium'
        | 'battery-plus'
        | 'battery-warning'
        | 'battery'
        | 'beaker'
        | 'bean-off'
        | 'bean'
        | 'bed-double'
        | 'bed-single'
        | 'bed'
        | 'beef'
        | 'beer-off'
        | 'beer'
        | 'bell-dot'
        | 'bell-electric'
        | 'bell-minus'
        | 'bell-off'
        | 'bell-plus'
        | 'bell-ring'
        | 'bell'
        | 'between-horizontal-end'
        | 'between-horizonal-end'
        | 'between-horizontal-start'
        | 'between-horizonal-start'
        | 'between-vertical-end'
        | 'between-vertical-start'
        | 'biceps-flexed'
        | 'bike'
        | 'binary'
        | 'binoculars'
        | 'biohazard'
        | 'bird'
        | 'bitcoin'
        | 'blend'
        | 'blinds'
        | 'blocks'
        | 'bluetooth-connected'
        | 'bluetooth-off'
        | 'bluetooth-searching'
        | 'bluetooth'
        | 'bold'
        | 'bolt'
        | 'bomb'
        | 'bone'
        | 'book-a'
        | 'book-alert'
        | 'book-audio'
        | 'book-check'
        | 'book-copy'
        | 'book-dashed'
        | 'book-template'
        | 'book-down'
        | 'book-headphones'
        | 'book-heart'
        | 'book-image'
        | 'book-key'
        | 'book-lock'
        | 'book-marked'
        | 'book-minus'
        | 'book-open-check'
        | 'book-open-text'
        | 'book-open'
        | 'book-plus'
        | 'book-text'
        | 'book-type'
        | 'book-up-2'
        | 'book-up'
        | 'book-user'
        | 'book-x'
        | 'book'
        | 'bookmark-check'
        | 'bookmark-minus'
        | 'bookmark-plus'
        | 'bookmark-x'
        | 'bookmark'
        | 'boom-box'
        | 'bot-message-square'
        | 'bot-off'
        | 'bot'
        | 'bottle-wine'
        | 'bow-arrow'
        | 'box'
        | 'boxes'
        | 'braces'
        | 'curly-braces'
        | 'brackets'
        | 'brain-circuit'
        | 'brain-cog'
        | 'brain'
        | 'brick-wall-fire'
        | 'brick-wall-shield'
        | 'brick-wall'
        | 'briefcase-business'
        | 'briefcase-conveyor-belt'
        | 'briefcase-medical'
        | 'briefcase'
        | 'bring-to-front'
        | 'brush-cleaning'
        | 'brush'
        | 'bubbles'
        | 'bug-off'
        | 'bug-play'
        | 'bug'
        | 'building-2'
        | 'building'
        | 'bus-front'
        | 'bus'
        | 'cable-car'
        | 'cable'
        | 'cake-slice'
        | 'cake'
        | 'calculator'
        | 'calendar-1'
        | 'calendar-arrow-down'
        | 'calendar-arrow-up'
        | 'calendar-check-2'
        | 'calendar-check'
        | 'calendar-clock'
        | 'calendar-cog'
        | 'calendar-days'
        | 'calendar-fold'
        | 'calendar-heart'
        | 'calendar-minus-2'
        | 'calendar-minus'
        | 'calendar-off'
        | 'calendar-plus-2'
        | 'calendar-plus'
        | 'calendar-range'
        | 'calendar-search'
        | 'calendar-sync'
        | 'calendar-x-2'
        | 'calendar-x'
        | 'calendar'
        | 'camera-off'
        | 'camera'
        | 'candy-cane'
        | 'candy-off'
        | 'candy'
        | 'cannabis'
        | 'captions-off'
        | 'captions'
        | 'subtitles'
        | 'car-front'
        | 'car-taxi-front'
        | 'car'
        | 'caravan'
        | 'card-sim'
        | 'carrot'
        | 'case-lower'
        | 'case-sensitive'
        | 'case-upper'
        | 'cassette-tape'
        | 'cast'
        | 'castle'
        | 'cat'
        | 'cctv'
        | 'chart-area'
        | 'area-chart'
        | 'chart-bar-big'
        | 'bar-chart-horizontal-big'
        | 'chart-bar-decreasing'
        | 'chart-bar-increasing'
        | 'chart-bar-stacked'
        | 'chart-bar'
        | 'bar-chart-horizontal'
        | 'chart-candlestick'
        | 'candlestick-chart'
        | 'chart-column-big'
        | 'bar-chart-big'
        | 'chart-column-decreasing'
        | 'chart-column-increasing'
        | 'bar-chart-4'
        | 'chart-column-stacked'
        | 'chart-column'
        | 'bar-chart-3'
        | 'chart-gantt'
        | 'chart-line'
        | 'line-chart'
        | 'chart-network'
        | 'chart-no-axes-column-decreasing'
        | 'chart-no-axes-column-increasing'
        | 'bar-chart'
        | 'chart-no-axes-column'
        | 'bar-chart-2'
        | 'chart-no-axes-combined'
        | 'chart-no-axes-gantt'
        | 'gantt-chart'
        | 'chart-pie'
        | 'pie-chart'
        | 'chart-scatter'
        | 'scatter-chart'
        | 'chart-spline'
        | 'check-check'
        | 'check-line'
        | 'check'
        | 'chef-hat'
        | 'cherry'
        | 'chevron-down'
        | 'chevron-first'
        | 'chevron-last'
        | 'chevron-left'
        | 'chevron-right'
        | 'chevron-up'
        | 'chevrons-down-up'
        | 'chevrons-down'
        | 'chevrons-left-right-ellipsis'
        | 'chevrons-left-right'
        | 'chevrons-left'
        | 'chevrons-right-left'
        | 'chevrons-right'
        | 'chevrons-up-down'
        | 'chevrons-up'
        | 'chromium'
        | 'chrome'
        | 'church'
        | 'cigarette-off'
        | 'cigarette'
        | 'circle-alert'
        | 'alert-circle'
        | 'circle-arrow-down'
        | 'arrow-down-circle'
        | 'circle-arrow-left'
        | 'arrow-left-circle'
        | 'circle-arrow-out-down-left'
        | 'arrow-down-left-from-circle'
        | 'circle-arrow-out-down-right'
        | 'arrow-down-right-from-circle'
        | 'circle-arrow-out-up-left'
        | 'arrow-up-left-from-circle'
        | 'circle-arrow-out-up-right'
        | 'arrow-up-right-from-circle'
        | 'circle-arrow-right'
        | 'arrow-right-circle'
        | 'circle-arrow-up'
        | 'arrow-up-circle'
        | 'circle-check-big'
        | 'check-circle'
        | 'circle-check'
        | 'check-circle-2'
        | 'circle-chevron-down'
        | 'chevron-down-circle'
        | 'circle-chevron-left'
        | 'chevron-left-circle'
        | 'circle-chevron-right'
        | 'chevron-right-circle'
        | 'circle-chevron-up'
        | 'chevron-up-circle'
        | 'circle-dashed'
        | 'circle-divide'
        | 'divide-circle'
        | 'circle-dollar-sign'
        | 'circle-dot-dashed'
        | 'circle-dot'
        | 'circle-ellipsis'
        | 'circle-equal'
        | 'circle-fading-arrow-up'
        | 'circle-fading-plus'
        | 'circle-gauge'
        | 'gauge-circle'
        | 'circle-minus'
        | 'minus-circle'
        | 'circle-off'
        | 'circle-parking-off'
        | 'parking-circle-off'
        | 'circle-parking'
        | 'parking-circle'
        | 'circle-pause'
        | 'pause-circle'
        | 'circle-percent'
        | 'percent-circle'
        | 'circle-play'
        | 'play-circle'
        | 'circle-plus'
        | 'plus-circle'
        | 'circle-pound-sterling'
        | 'circle-power'
        | 'power-circle'
        | 'circle-question-mark'
        | 'help-circle'
        | 'circle-help'
        | 'circle-slash-2'
        | 'circle-slashed'
        | 'circle-slash'
        | 'circle-small'
        | 'circle-star'
        | 'circle-stop'
        | 'stop-circle'
        | 'circle-user-round'
        | 'user-circle-2'
        | 'circle-user'
        | 'user-circle'
        | 'circle-x'
        | 'x-circle'
        | 'circle'
        | 'circuit-board'
        | 'citrus'
        | 'clapperboard'
        | 'clipboard-check'
        | 'clipboard-clock'
        | 'clipboard-copy'
        | 'clipboard-list'
        | 'clipboard-minus'
        | 'clipboard-paste'
        | 'clipboard-pen-line'
        | 'clipboard-signature'
        | 'clipboard-pen'
        | 'clipboard-edit'
        | 'clipboard-plus'
        | 'clipboard-type'
        | 'clipboard-x'
        | 'clipboard'
        | 'clock-1'
        | 'clock-10'
        | 'clock-11'
        | 'clock-12'
        | 'clock-2'
        | 'clock-3'
        | 'clock-4'
        | 'clock-5'
        | 'clock-6'
        | 'clock-7'
        | 'clock-8'
        | 'clock-9'
        | 'clock-alert'
        | 'clock-arrow-down'
        | 'clock-arrow-up'
        | 'clock-fading'
        | 'clock-plus'
        | 'clock'
        | 'closed-caption'
        | 'cloud-alert'
        | 'cloud-check'
        | 'cloud-cog'
        | 'cloud-download'
        | 'download-cloud'
        | 'cloud-drizzle'
        | 'cloud-fog'
        | 'cloud-hail'
        | 'cloud-lightning'
        | 'cloud-moon-rain'
        | 'cloud-moon'
        | 'cloud-off'
        | 'cloud-rain-wind'
        | 'cloud-rain'
        | 'cloud-snow'
        | 'cloud-sun-rain'
        | 'cloud-sun'
        | 'cloud-upload'
        | 'upload-cloud'
        | 'cloud'
        | 'cloudy'
        | 'clover'
        | 'club'
        | 'code-xml'
        | 'code-2'
        | 'code'
        | 'codepen'
        | 'codesandbox'
        | 'coffee'
        | 'cog'
        | 'coins'
        | 'columns-2'
        | 'columns'
        | 'columns-3-cog'
        | 'columns-settings'
        | 'table-config'
        | 'columns-3'
        | 'panels-left-right'
        | 'columns-4'
        | 'combine'
        | 'command'
        | 'compass'
        | 'component'
        | 'computer'
        | 'concierge-bell'
        | 'cone'
        | 'construction'
        | 'contact-round'
        | 'contact-2'
        | 'contact'
        | 'container'
        | 'contrast'
        | 'cookie'
        | 'cooking-pot'
        | 'copy-check'
        | 'copy-minus'
        | 'copy-plus'
        | 'copy-slash'
        | 'copy-x'
        | 'copy'
        | 'copyleft'
        | 'copyright'
        | 'corner-down-left'
        | 'corner-down-right'
        | 'corner-left-down'
        | 'corner-left-up'
        | 'corner-right-down'
        | 'corner-right-up'
        | 'corner-up-left'
        | 'corner-up-right'
        | 'cpu'
        | 'creative-commons'
        | 'credit-card'
        | 'croissant'
        | 'crop'
        | 'cross'
        | 'crosshair'
        | 'crown'
        | 'cuboid'
        | 'cup-soda'
        | 'currency'
        | 'cylinder'
        | 'dam'
        | 'database-backup'
        | 'database-zap'
        | 'database'
        | 'decimals-arrow-left'
        | 'decimals-arrow-right'
        | 'delete'
        | 'dessert'
        | 'diameter'
        | 'diamond-minus'
        | 'diamond-percent'
        | 'percent-diamond'
        | 'diamond-plus'
        | 'diamond'
        | 'dice-1'
        | 'dice-2'
        | 'dice-3'
        | 'dice-4'
        | 'dice-5'
        | 'dice-6'
        | 'dices'
        | 'diff'
        | 'disc-2'
        | 'disc-3'
        | 'disc-album'
        | 'disc'
        | 'divide'
        | 'dna-off'
        | 'dna'
        | 'dock'
        | 'dog'
        | 'dollar-sign'
        | 'donut'
        | 'door-closed-locked'
        | 'door-closed'
        | 'door-open'
        | 'dot'
        | 'download'
        | 'drafting-compass'
        | 'drama'
        | 'dribbble'
        | 'drill'
        | 'drone'
        | 'droplet-off'
        | 'droplet'
        | 'droplets'
        | 'drum'
        | 'drumstick'
        | 'dumbbell'
        | 'ear-off'
        | 'ear'
        | 'earth-lock'
        | 'earth'
        | 'globe-2'
        | 'eclipse'
        | 'egg-fried'
        | 'egg-off'
        | 'egg'
        | 'ellipsis-vertical'
        | 'more-vertical'
        | 'ellipsis'
        | 'more-horizontal'
        | 'equal-approximately'
        | 'equal-not'
        | 'equal'
        | 'eraser'
        | 'ethernet-port'
        | 'euro'
        | 'expand'
        | 'external-link'
        | 'eye-closed'
        | 'eye-off'
        | 'eye'
        | 'facebook'
        | 'factory'
        | 'fan'
        | 'fast-forward'
        | 'feather'
        | 'fence'
        | 'ferris-wheel'
        | 'figma'
        | 'file-archive'
        | 'file-audio-2'
        | 'file-audio'
        | 'file-axis-3d'
        | 'file-axis-3-d'
        | 'file-badge-2'
        | 'file-badge'
        | 'file-box'
        | 'file-chart-column-increasing'
        | 'file-bar-chart'
        | 'file-chart-column'
        | 'file-bar-chart-2'
        | 'file-chart-line'
        | 'file-line-chart'
        | 'file-chart-pie'
        | 'file-pie-chart'
        | 'file-check-2'
        | 'file-check'
        | 'file-clock'
        | 'file-code-2'
        | 'file-code'
        | 'file-cog'
        | 'file-cog-2'
        | 'file-diff'
        | 'file-digit'
        | 'file-down'
        | 'file-heart'
        | 'file-image'
        | 'file-input'
        | 'file-json-2'
        | 'file-json'
        | 'file-key-2'
        | 'file-key'
        | 'file-lock-2'
        | 'file-lock'
        | 'file-minus-2'
        | 'file-minus'
        | 'file-music'
        | 'file-output'
        | 'file-pen-line'
        | 'file-signature'
        | 'file-pen'
        | 'file-edit'
        | 'file-play'
        | 'file-video'
        | 'file-plus-2'
        | 'file-plus'
        | 'file-question-mark'
        | 'file-question'
        | 'file-scan'
        | 'file-search-2'
        | 'file-search'
        | 'file-sliders'
        | 'file-spreadsheet'
        | 'file-stack'
        | 'file-symlink'
        | 'file-terminal'
        | 'file-text'
        | 'file-type-2'
        | 'file-type'
        | 'file-up'
        | 'file-user'
        | 'file-video-camera'
        | 'file-video-2'
        | 'file-volume-2'
        | 'file-volume'
        | 'file-warning'
        | 'file-x-2'
        | 'file-x'
        | 'file'
        | 'files'
        | 'film'
        | 'fingerprint'
        | 'fire-extinguisher'
        | 'fish-off'
        | 'fish-symbol'
        | 'fish'
        | 'flag-off'
        | 'flag-triangle-left'
        | 'flag-triangle-right'
        | 'flag'
        | 'flame-kindling'
        | 'flame'
        | 'flashlight-off'
        | 'flashlight'
        | 'flask-conical-off'
        | 'flask-conical'
        | 'flask-round'
        | 'flip-horizontal-2'
        | 'flip-horizontal'
        | 'flip-vertical-2'
        | 'flip-vertical'
        | 'flower-2'
        | 'flower'
        | 'focus'
        | 'fold-horizontal'
        | 'fold-vertical'
        | 'folder-archive'
        | 'folder-check'
        | 'folder-clock'
        | 'folder-closed'
        | 'folder-code'
        | 'folder-cog'
        | 'folder-cog-2'
        | 'folder-dot'
        | 'folder-down'
        | 'folder-git-2'
        | 'folder-git'
        | 'folder-heart'
        | 'folder-input'
        | 'folder-kanban'
        | 'folder-key'
        | 'folder-lock'
        | 'folder-minus'
        | 'folder-open-dot'
        | 'folder-open'
        | 'folder-output'
        | 'folder-pen'
        | 'folder-edit'
        | 'folder-plus'
        | 'folder-root'
        | 'folder-search-2'
        | 'folder-search'
        | 'folder-symlink'
        | 'folder-sync'
        | 'folder-tree'
        | 'folder-up'
        | 'folder-x'
        | 'folder'
        | 'folders'
        | 'footprints'
        | 'forklift'
        | 'forward'
        | 'frame'
        | 'framer'
        | 'frown'
        | 'fuel'
        | 'fullscreen'
        | 'funnel-plus'
        | 'funnel-x'
        | 'filter-x'
        | 'funnel'
        | 'filter'
        | 'gallery-horizontal-end'
        | 'gallery-horizontal'
        | 'gallery-thumbnails'
        | 'gallery-vertical-end'
        | 'gallery-vertical'
        | 'gamepad-2'
        | 'gamepad'
        | 'gauge'
        | 'gavel'
        | 'gem'
        | 'georgian-lari'
        | 'ghost'
        | 'gift'
        | 'git-branch-plus'
        | 'git-branch'
        | 'git-commit-horizontal'
        | 'git-commit'
        | 'git-commit-vertical'
        | 'git-compare-arrows'
        | 'git-compare'
        | 'git-fork'
        | 'git-graph'
        | 'git-merge'
        | 'git-pull-request-arrow'
        | 'git-pull-request-closed'
        | 'git-pull-request-create-arrow'
        | 'git-pull-request-create'
        | 'git-pull-request-draft'
        | 'git-pull-request'
        | 'github'
        | 'gitlab'
        | 'glass-water'
        | 'glasses'
        | 'globe-lock'
        | 'globe'
        | 'goal'
        | 'gpu'
        | 'graduation-cap'
        | 'grape'
        | 'grid-2x2-check'
        | 'grid-2-x-2-check'
        | 'grid-2x2-plus'
        | 'grid-2-x-2-plus'
        | 'grid-2x2-x'
        | 'grid-2-x-2-x'
        | 'grid-2x2'
        | 'grid-2-x-2'
        | 'grid-3x2'
        | 'grid-3x3'
        | 'grid'
        | 'grid-3-x-3'
        | 'grip-horizontal'
        | 'grip-vertical'
        | 'grip'
        | 'group'
        | 'guitar'
        | 'ham'
        | 'hamburger'
        | 'hammer'
        | 'hand-coins'
        | 'hand-fist'
        | 'hand-grab'
        | 'grab'
        | 'hand-heart'
        | 'hand-helping'
        | 'helping-hand'
        | 'hand-metal'
        | 'hand-platter'
        | 'hand'
        | 'handbag'
        | 'handshake'
        | 'hard-drive-download'
        | 'hard-drive-upload'
        | 'hard-drive'
        | 'hard-hat'
        | 'hash'
        | 'hat-glasses'
        | 'haze'
        | 'hdmi-port'
        | 'heading-1'
        | 'heading-2'
        | 'heading-3'
        | 'heading-4'
        | 'heading-5'
        | 'heading-6'
        | 'heading'
        | 'headphone-off'
        | 'headphones'
        | 'headset'
        | 'heart-crack'
        | 'heart-handshake'
        | 'heart-minus'
        | 'heart-off'
        | 'heart-plus'
        | 'heart-pulse'
        | 'heart'
        | 'heater'
        | 'hexagon'
        | 'highlighter'
        | 'history'
        | 'hop-off'
        | 'hop'
        | 'hospital'
        | 'hotel'
        | 'hourglass'
        | 'house-plug'
        | 'house-plus'
        | 'house-wifi'
        | 'house'
        | 'home'
        | 'ice-cream-bowl'
        | 'ice-cream-2'
        | 'ice-cream-cone'
        | 'ice-cream'
        | 'id-card-lanyard'
        | 'id-card'
        | 'image-down'
        | 'image-minus'
        | 'image-off'
        | 'image-play'
        | 'image-plus'
        | 'image-up'
        | 'image-upscale'
        | 'image'
        | 'images'
        | 'import'
        | 'inbox'
        | 'indent-decrease'
        | 'outdent'
        | 'indent-increase'
        | 'indent'
        | 'indian-rupee'
        | 'infinity'
        | 'info'
        | 'inspection-panel'
        | 'instagram'
        | 'italic'
        | 'iteration-ccw'
        | 'iteration-cw'
        | 'japanese-yen'
        | 'joystick'
        | 'kanban'
        | 'kayak'
        | 'key-round'
        | 'key-square'
        | 'key'
        | 'keyboard-music'
        | 'keyboard-off'
        | 'keyboard'
        | 'lamp-ceiling'
        | 'lamp-desk'
        | 'lamp-floor'
        | 'lamp-wall-down'
        | 'lamp-wall-up'
        | 'lamp'
        | 'land-plot'
        | 'landmark'
        | 'languages'
        | 'laptop-minimal-check'
        | 'laptop-minimal'
        | 'laptop-2'
        | 'laptop'
        | 'lasso-select'
        | 'lasso'
        | 'laugh'
        | 'layers-2'
        | 'layers'
        | 'layers-3'
        | 'layout-dashboard'
        | 'layout-grid'
        | 'layout-list'
        | 'layout-panel-left'
        | 'layout-panel-top'
        | 'layout-template'
        | 'leaf'
        | 'leafy-green'
        | 'lectern'
        | 'letter-text'
        | 'library-big'
        | 'library'
        | 'life-buoy'
        | 'ligature'
        | 'lightbulb-off'
        | 'lightbulb'
        | 'line-squiggle'
        | 'link-2-off'
        | 'link-2'
        | 'link'
        | 'linkedin'
        | 'list-check'
        | 'list-checks'
        | 'list-chevrons-down-up'
        | 'list-collapse'
        | 'list-end'
        | 'list-filter-plus'
        | 'list-filter'
        | 'list-minus'
        | 'list-music'
        | 'list-ordered'
        | 'list-plus'
        | 'list-restart'
        | 'list-start'
        | 'list-todo'
        | 'list-tree'
        | 'list-video'
        | 'list-x'
        | 'list'
        | 'loader-circle'
        | 'loader-2'
        | 'loader-pinwheel'
        | 'loader'
        | 'locate-fixed'
        | 'locate-off'
        | 'locate'
        | 'lock-keyhole-open'
        | 'unlock-keyhole'
        | 'lock-keyhole'
        | 'lock-open'
        | 'unlock'
        | 'lock'
        | 'log-in'
        | 'log-out'
        | 'logs'
        | 'lollipop'
        | 'luggage'
        | 'magnet'
        | 'mail-check'
        | 'mail-minus'
        | 'mail-open'
        | 'mail-plus'
        | 'mail-question-mark'
        | 'mail-question'
        | 'mail-search'
        | 'mail-warning'
        | 'mail-x'
        | 'mail'
        | 'mailbox'
        | 'mails'
        | 'map-minus'
        | 'map-pin-check-inside'
        | 'map-pin-check'
        | 'map-pin-house'
        | 'map-pin-minus-inside'
        | 'map-pin-minus'
        | 'map-pin-off'
        | 'map-pin-pen'
        | 'location-edit'
        | 'map-pin-plus-inside'
        | 'map-pin-plus'
        | 'map-pin-x-inside'
        | 'map-pin-x'
        | 'map-pin'
        | 'map-pinned'
        | 'map-plus'
        | 'map'
        | 'mars-stroke'
        | 'mars'
        | 'martini'
        | 'maximize-2'
        | 'maximize'
        | 'medal'
        | 'megaphone-off'
        | 'megaphone'
        | 'meh'
        | 'memory-stick'
        | 'menu'
        | 'merge'
        | 'message-circle-code'
        | 'message-circle-dashed'
        | 'message-circle-heart'
        | 'message-circle-more'
        | 'message-circle-off'
        | 'message-circle-plus'
        | 'message-circle-question-mark'
        | 'message-circle-question'
        | 'message-circle-reply'
        | 'message-circle-warning'
        | 'message-circle-x'
        | 'message-circle'
        | 'message-square-code'
        | 'message-square-dashed'
        | 'message-square-diff'
        | 'message-square-dot'
        | 'message-square-heart'
        | 'message-square-lock'
        | 'message-square-more'
        | 'message-square-off'
        | 'message-square-plus'
        | 'message-square-quote'
        | 'message-square-reply'
        | 'message-square-share'
        | 'message-square-text'
        | 'message-square-warning'
        | 'message-square-x'
        | 'message-square'
        | 'messages-square'
        | 'mic-off'
        | 'mic-vocal'
        | 'mic-2'
        | 'mic'
        | 'microchip'
        | 'microscope'
        | 'microwave'
        | 'milestone'
        | 'milk-off'
        | 'milk'
        | 'minimize-2'
        | 'minimize'
        | 'minus'
        | 'monitor-check'
        | 'monitor-cog'
        | 'monitor-dot'
        | 'monitor-down'
        | 'monitor-off'
        | 'monitor-pause'
        | 'monitor-play'
        | 'monitor-smartphone'
        | 'monitor-speaker'
        | 'monitor-stop'
        | 'monitor-up'
        | 'monitor-x'
        | 'monitor'
        | 'moon-star'
        | 'moon'
        | 'mountain-snow'
        | 'mountain'
        | 'mouse-off'
        | 'mouse-pointer-2'
        | 'mouse-pointer-ban'
        | 'mouse-pointer-click'
        | 'mouse-pointer'
        | 'mouse'
        | 'move-3d'
        | 'move-3-d'
        | 'move-diagonal-2'
        | 'move-diagonal'
        | 'move-down-left'
        | 'move-down-right'
        | 'move-down'
        | 'move-horizontal'
        | 'move-left'
        | 'move-right'
        | 'move-up-left'
        | 'move-up-right'
        | 'move-up'
        | 'move-vertical'
        | 'move'
        | 'music-2'
        | 'music-3'
        | 'music-4'
        | 'music'
        | 'navigation-2-off'
        | 'navigation-2'
        | 'navigation-off'
        | 'navigation'
        | 'network'
        | 'newspaper'
        | 'nfc'
        | 'non-binary'
        | 'notebook-pen'
        | 'notebook-tabs'
        | 'notebook-text'
        | 'notebook'
        | 'notepad-text-dashed'
        | 'notepad-text'
        | 'nut-off'
        | 'nut'
        | 'octagon-alert'
        | 'alert-octagon'
        | 'octagon-minus'
        | 'octagon-pause'
        | 'pause-octagon'
        | 'octagon-x'
        | 'x-octagon'
        | 'octagon'
        | 'omega'
        | 'option'
        | 'orbit'
        | 'origami'
        | 'package-2'
        | 'package-check'
        | 'package-minus'
        | 'package-open'
        | 'package-plus'
        | 'package-search'
        | 'package-x'
        | 'package'
        | 'paint-bucket'
        | 'paint-roller'
        | 'paintbrush-vertical'
        | 'paintbrush-2'
        | 'paintbrush'
        | 'palette'
        | 'panda'
        | 'panel-bottom-close'
        | 'panel-bottom-dashed'
        | 'panel-bottom-inactive'
        | 'panel-bottom-open'
        | 'panel-bottom'
        | 'panel-left-close'
        | 'sidebar-close'
        | 'panel-left-dashed'
        | 'panel-left-inactive'
        | 'panel-left-open'
        | 'sidebar-open'
        | 'panel-left-right-dashed'
        | 'panel-left'
        | 'sidebar'
        | 'panel-right-close'
        | 'panel-right-dashed'
        | 'panel-right-inactive'
        | 'panel-right-open'
        | 'panel-right'
        | 'panel-top-bottom-dashed'
        | 'panel-top-close'
        | 'panel-top-dashed'
        | 'panel-top-inactive'
        | 'panel-top-open'
        | 'panel-top'
        | 'panels-left-bottom'
        | 'panels-right-bottom'
        | 'panels-top-left'
        | 'layout'
        | 'paperclip'
        | 'parentheses'
        | 'parking-meter'
        | 'party-popper'
        | 'pause'
        | 'paw-print'
        | 'pc-case'
        | 'pen-line'
        | 'edit-3'
        | 'pen-off'
        | 'pen-tool'
        | 'pen'
        | 'edit-2'
        | 'pencil-line'
        | 'pencil-off'
        | 'pencil-ruler'
        | 'pencil'
        | 'pentagon'
        | 'percent'
        | 'person-standing'
        | 'philippine-peso'
        | 'phone-call'
        | 'phone-forwarded'
        | 'phone-incoming'
        | 'phone-missed'
        | 'phone-off'
        | 'phone-outgoing'
        | 'phone'
        | 'pi'
        | 'piano'
        | 'pickaxe'
        | 'picture-in-picture-2'
        | 'picture-in-picture'
        | 'piggy-bank'
        | 'pilcrow-left'
        | 'pilcrow-right'
        | 'pilcrow'
        | 'pill-bottle'
        | 'pill'
        | 'pin-off'
        | 'pin'
        | 'pipette'
        | 'pizza'
        | 'plane-landing'
        | 'plane-takeoff'
        | 'plane'
        | 'play'
        | 'plug-2'
        | 'plug-zap'
        | 'plug-zap-2'
        | 'plug'
        | 'plus'
        | 'pocket-knife'
        | 'pocket'
        | 'podcast'
        | 'pointer-off'
        | 'pointer'
        | 'popcorn'
        | 'popsicle'
        | 'pound-sterling'
        | 'power-off'
        | 'power'
        | 'presentation'
        | 'printer-check'
        | 'printer'
        | 'projector'
        | 'proportions'
        | 'puzzle'
        | 'pyramid'
        | 'qr-code'
        | 'quote'
        | 'rabbit'
        | 'radar'
        | 'radiation'
        | 'radical'
        | 'radio-receiver'
        | 'radio-tower'
        | 'radio'
        | 'radius'
        | 'rail-symbol'
        | 'rainbow'
        | 'rat'
        | 'ratio'
        | 'receipt-cent'
        | 'receipt-euro'
        | 'receipt-indian-rupee'
        | 'receipt-japanese-yen'
        | 'receipt-pound-sterling'
        | 'receipt-russian-ruble'
        | 'receipt-swiss-franc'
        | 'receipt-text'
        | 'receipt-turkish-lira'
        | 'receipt'
        | 'rectangle-circle'
        | 'rectangle-ellipsis'
        | 'form-input'
        | 'rectangle-goggles'
        | 'rectangle-horizontal'
        | 'rectangle-vertical'
        | 'recycle'
        | 'redo-2'
        | 'redo-dot'
        | 'redo'
        | 'refresh-ccw-dot'
        | 'refresh-ccw'
        | 'refresh-cw-off'
        | 'refresh-cw'
        | 'refrigerator'
        | 'regex'
        | 'remove-formatting'
        | 'repeat-1'
        | 'repeat-2'
        | 'repeat'
        | 'replace-all'
        | 'replace'
        | 'reply-all'
        | 'reply'
        | 'rewind'
        | 'ribbon'
        | 'rocket'
        | 'rocking-chair'
        | 'roller-coaster'
        | 'rose'
        | 'rotate-3d'
        | 'rotate-3-d'
        | 'rotate-ccw-key'
        | 'rotate-ccw-square'
        | 'rotate-ccw'
        | 'rotate-cw-square'
        | 'rotate-cw'
        | 'route-off'
        | 'route'
        | 'router'
        | 'rows-2'
        | 'rows'
        | 'rows-3'
        | 'panels-top-bottom'
        | 'rows-4'
        | 'rss'
        | 'ruler-dimension-line'
        | 'ruler'
        | 'russian-ruble'
        | 'sailboat'
        | 'salad'
        | 'sandwich'
        | 'satellite-dish'
        | 'satellite'
        | 'saudi-riyal'
        | 'save-all'
        | 'save-off'
        | 'save'
        | 'scale-3d'
        | 'scale-3-d'
        | 'scale'
        | 'scaling'
        | 'scan-barcode'
        | 'scan-eye'
        | 'scan-face'
        | 'scan-heart'
        | 'scan-line'
        | 'scan-qr-code'
        | 'scan-search'
        | 'scan-text'
        | 'scan'
        | 'school'
        | 'scissors-line-dashed'
        | 'scissors'
        | 'screen-share-off'
        | 'screen-share'
        | 'scroll-text'
        | 'scroll'
        | 'search-check'
        | 'search-code'
        | 'search-slash'
        | 'search-x'
        | 'search'
        | 'section'
        | 'send-horizontal'
        | 'send-horizonal'
        | 'send-to-back'
        | 'send'
        | 'separator-horizontal'
        | 'separator-vertical'
        | 'server-cog'
        | 'server-crash'
        | 'server-off'
        | 'server'
        | 'settings-2'
        | 'settings'
        | 'shapes'
        | 'share-2'
        | 'share'
        | 'sheet'
        | 'shell'
        | 'shield-alert'
        | 'shield-ban'
        | 'shield-check'
        | 'shield-ellipsis'
        | 'shield-half'
        | 'shield-minus'
        | 'shield-off'
        | 'shield-plus'
        | 'shield-question-mark'
        | 'shield-question'
        | 'shield-user'
        | 'shield-x'
        | 'shield-close'
        | 'shield'
        | 'ship-wheel'
        | 'ship'
        | 'shirt'
        | 'shopping-bag'
        | 'shopping-basket'
        | 'shopping-cart'
        | 'shovel'
        | 'shower-head'
        | 'shredder'
        | 'shrimp'
        | 'shrink'
        | 'shrub'
        | 'shuffle'
        | 'sigma'
        | 'signal-high'
        | 'signal-low'
        | 'signal-medium'
        | 'signal-zero'
        | 'signal'
        | 'signature'
        | 'signpost-big'
        | 'signpost'
        | 'siren'
        | 'skip-back'
        | 'skip-forward'
        | 'skull'
        | 'slack'
        | 'slash'
        | 'slice'
        | 'sliders-horizontal'
        | 'sliders-vertical'
        | 'sliders'
        | 'smartphone-charging'
        | 'smartphone-nfc'
        | 'smartphone'
        | 'smile-plus'
        | 'smile'
        | 'snail'
        | 'snowflake'
        | 'soap-dispenser-droplet'
        | 'sofa'
        | 'soup'
        | 'space'
        | 'spade'
        | 'sparkle'
        | 'sparkles'
        | 'stars'
        | 'speaker'
        | 'speech'
        | 'spell-check-2'
        | 'spell-check'
        | 'spline-pointer'
        | 'spline'
        | 'split'
        | 'spool'
        | 'spotlight'
        | 'spray-can'
        | 'sprout'
        | 'square-activity'
        | 'activity-square'
        | 'square-arrow-down-left'
        | 'arrow-down-left-square'
        | 'square-arrow-down-right'
        | 'arrow-down-right-square'
        | 'square-arrow-down'
        | 'arrow-down-square'
        | 'square-arrow-left'
        | 'arrow-left-square'
        | 'square-arrow-out-down-left'
        | 'arrow-down-left-from-square'
        | 'square-arrow-out-down-right'
        | 'arrow-down-right-from-square'
        | 'square-arrow-out-up-left'
        | 'arrow-up-left-from-square'
        | 'square-arrow-out-up-right'
        | 'arrow-up-right-from-square'
        | 'square-arrow-right'
        | 'arrow-right-square'
        | 'square-arrow-up-left'
        | 'arrow-up-left-square'
        | 'square-arrow-up-right'
        | 'arrow-up-right-square'
        | 'square-arrow-up'
        | 'arrow-up-square'
        | 'square-asterisk'
        | 'asterisk-square'
        | 'square-bottom-dashed-scissors'
        | 'scissors-square-dashed-bottom'
        | 'square-chart-gantt'
        | 'gantt-chart-square'
        | 'square-gantt-chart'
        | 'square-check-big'
        | 'check-square'
        | 'square-check'
        | 'check-square-2'
        | 'square-chevron-down'
        | 'chevron-down-square'
        | 'square-chevron-left'
        | 'chevron-left-square'
        | 'square-chevron-right'
        | 'chevron-right-square'
        | 'square-chevron-up'
        | 'chevron-up-square'
        | 'square-code'
        | 'code-square'
        | 'square-dashed-bottom-code'
        | 'square-dashed-bottom'
        | 'square-dashed-kanban'
        | 'kanban-square-dashed'
        | 'square-dashed-mouse-pointer'
        | 'mouse-pointer-square-dashed'
        | 'square-dashed-top-solid'
        | 'square-dashed'
        | 'box-select'
        | 'square-divide'
        | 'divide-square'
        | 'square-dot'
        | 'dot-square'
        | 'square-equal'
        | 'equal-square'
        | 'square-function'
        | 'function-square'
        | 'square-kanban'
        | 'kanban-square'
        | 'square-library'
        | 'library-square'
        | 'square-m'
        | 'm-square'
        | 'square-menu'
        | 'menu-square'
        | 'square-minus'
        | 'minus-square'
        | 'square-mouse-pointer'
        | 'inspect'
        | 'square-parking-off'
        | 'parking-square-off'
        | 'square-parking'
        | 'parking-square'
        | 'square-pause'
        | 'square-pen'
        | 'pen-box'
        | 'edit'
        | 'pen-square'
        | 'square-percent'
        | 'percent-square'
        | 'square-pi'
        | 'pi-square'
        | 'square-pilcrow'
        | 'pilcrow-square'
        | 'square-play'
        | 'play-square'
        | 'square-plus'
        | 'plus-square'
        | 'square-power'
        | 'power-square'
        | 'square-radical'
        | 'square-round-corner'
        | 'square-scissors'
        | 'scissors-square'
        | 'square-sigma'
        | 'sigma-square'
        | 'square-slash'
        | 'slash-square'
        | 'square-split-horizontal'
        | 'split-square-horizontal'
        | 'square-split-vertical'
        | 'split-square-vertical'
        | 'square-square'
        | 'square-stack'
        | 'square-star'
        | 'square-stop'
        | 'square-terminal'
        | 'terminal-square'
        | 'square-user-round'
        | 'user-square-2'
        | 'square-user'
        | 'user-square'
        | 'square-x'
        | 'x-square'
        | 'square'
        | 'squares-exclude'
        | 'squares-intersect'
        | 'squares-subtract'
        | 'squares-unite'
        | 'squircle-dashed'
        | 'squircle'
        | 'squirrel'
        | 'stamp'
        | 'star-half'
        | 'star-off'
        | 'star'
        | 'step-back'
        | 'step-forward'
        | 'stethoscope'
        | 'sticker'
        | 'sticky-note'
        | 'store'
        | 'stretch-horizontal'
        | 'stretch-vertical'
        | 'strikethrough'
        | 'subscript'
        | 'sun-dim'
        | 'sun-medium'
        | 'sun-moon'
        | 'sun-snow'
        | 'sun'
        | 'sunrise'
        | 'sunset'
        | 'superscript'
        | 'swatch-book'
        | 'swiss-franc'
        | 'switch-camera'
        | 'sword'
        | 'swords'
        | 'syringe'
        | 'table-2'
        | 'table-cells-merge'
        | 'table-cells-split'
        | 'table-columns-split'
        | 'table-of-contents'
        | 'table-properties'
        | 'table-rows-split'
        | 'table'
        | 'tablet-smartphone'
        | 'tablet'
        | 'tablets'
        | 'tag'
        | 'tags'
        | 'tally-1'
        | 'tally-2'
        | 'tally-3'
        | 'tally-4'
        | 'tally-5'
        | 'tangent'
        | 'target'
        | 'telescope'
        | 'tent-tree'
        | 'tent'
        | 'terminal'
        | 'test-tube-diagonal'
        | 'test-tube-2'
        | 'test-tube'
        | 'test-tubes'
        | 'text-cursor-input'
        | 'text-cursor'
        | 'text-quote'
        | 'text-search'
        | 'text-select'
        | 'text-selection'
        | 'text'
        | 'theater'
        | 'thermometer-snowflake'
        | 'thermometer-sun'
        | 'thermometer'
        | 'thumbs-down'
        | 'thumbs-up'
        | 'ticket-check'
        | 'ticket-minus'
        | 'ticket-percent'
        | 'ticket-plus'
        | 'ticket-slash'
        | 'ticket-x'
        | 'ticket'
        | 'tickets-plane'
        | 'tickets'
        | 'timer-off'
        | 'timer-reset'
        | 'timer'
        | 'toggle-left'
        | 'toggle-right'
        | 'toilet'
        | 'tool-case'
        | 'tornado'
        | 'torus'
        | 'touchpad-off'
        | 'touchpad'
        | 'tower-control'
        | 'toy-brick'
        | 'tractor'
        | 'traffic-cone'
        | 'train-front-tunnel'
        | 'train-front'
        | 'train-track'
        | 'tram-front'
        | 'train'
        | 'transgender'
        | 'trash-2'
        | 'trash'
        | 'tree-deciduous'
        | 'tree-palm'
        | 'palmtree'
        | 'tree-pine'
        | 'trees'
        | 'trello'
        | 'trending-down'
        | 'trending-up-down'
        | 'trending-up'
        | 'triangle-alert'
        | 'alert-triangle'
        | 'triangle-dashed'
        | 'triangle-right'
        | 'triangle'
        | 'trophy'
        | 'truck-electric'
        | 'truck'
        | 'turkish-lira'
        | 'turntable'
        | 'turtle'
        | 'tv-minimal-play'
        | 'tv-minimal'
        | 'tv-2'
        | 'tv'
        | 'twitch'
        | 'twitter'
        | 'type-outline'
        | 'type'
        | 'umbrella-off'
        | 'umbrella'
        | 'underline'
        | 'undo-2'
        | 'undo-dot'
        | 'undo'
        | 'unfold-horizontal'
        | 'unfold-vertical'
        | 'ungroup'
        | 'university'
        | 'school-2'
        | 'unlink-2'
        | 'unlink'
        | 'unplug'
        | 'upload'
        | 'usb'
        | 'user-check'
        | 'user-cog'
        | 'user-lock'
        | 'user-minus'
        | 'user-pen'
        | 'user-plus'
        | 'user-round-check'
        | 'user-check-2'
        | 'user-round-cog'
        | 'user-cog-2'
        | 'user-round-minus'
        | 'user-minus-2'
        | 'user-round-pen'
        | 'user-round-plus'
        | 'user-plus-2'
        | 'user-round-search'
        | 'user-round-x'
        | 'user-x-2'
        | 'user-round'
        | 'user-2'
        | 'user-search'
        | 'user-star'
        | 'user-x'
        | 'user'
        | 'users-round'
        | 'users-2'
        | 'users'
        | 'utensils-crossed'
        | 'fork-knife-crossed'
        | 'utensils'
        | 'fork-knife'
        | 'utility-pole'
        | 'variable'
        | 'vault'
        | 'vector-square'
        | 'vegan'
        | 'venetian-mask'
        | 'venus-and-mars'
        | 'venus'
        | 'vibrate-off'
        | 'vibrate'
        | 'video-off'
        | 'video'
        | 'videotape'
        | 'view'
        | 'voicemail'
        | 'volleyball'
        | 'volume-1'
        | 'volume-2'
        | 'volume-off'
        | 'volume-x'
        | 'volume'
        | 'vote'
        | 'wallet-cards'
        | 'wallet-minimal'
        | 'wallet-2'
        | 'wallet'
        | 'wallpaper'
        | 'wand-sparkles'
        | 'wand-2'
        | 'wand'
        | 'warehouse'
        | 'washing-machine'
        | 'watch'
        | 'waves-ladder'
        | 'waves'
        | 'waypoints'
        | 'webcam'
        | 'webhook-off'
        | 'webhook'
        | 'weight'
        | 'wheat-off'
        | 'wheat'
        | 'whole-word'
        | 'wifi-cog'
        | 'wifi-high'
        | 'wifi-low'
        | 'wifi-off'
        | 'wifi-pen'
        | 'wifi-sync'
        | 'wifi-zero'
        | 'wifi'
        | 'wind-arrow-down'
        | 'wind'
        | 'wine-off'
        | 'wine'
        | 'workflow'
        | 'worm'
        | 'wrap-text'
        | 'wrench'
        | 'x'
        | 'youtube'
        | 'zap-off'
        | 'zap'
        | 'zoom-in'
        | 'zoom-out'
      )
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (string | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: string | Product;
  options: (string | VariantOption)[];
  inventory?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (string | null) | User;
  customerEmail?: string | null;
  order?: (string | null) | Order;
  cart?: (string | null) | Cart;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (string | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer?: (string | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  refCategory?: T;
  icon?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  accessToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}